#!/bin/sh
# Freepto LiveBuild Config

lb config noauto \
    -a i386 \
    -b hdd \
    -d wheezy \
    --linux-flavours 686-pae \
    --security true \
    --apt-indices false \
    --mode debian \
    --memtest none \
    --source false \
    --backports true \
    --checksums sha256 \
    --system live \
    --apt-source-archives false \
    --debian-installer false \
    --bootappend-install noprompt \
    --bootappend-live "\
    boot=live \
    config \
    quickreboot \
    persistence-encryption=luks \
    persistence-media=removable-usb \
    username=paranoid \
    hostname=freepto \
    persistence \
    live-config.locales=it_IT.UTF-8 live-config.timezone=Europe/Rome live-config.keyboard-layouts=it \
    live-config.hooks=filesystem \
    " \
    --archive-areas "main contrib non-free" \
    --apt-recommends true \
"${@}"
