#!/usr/bin/env bash

if ! service tor status; then
	# tor is deactivated by the user!
	exit 0
fi

if curl -m 5 --socks5 127.0.0.1:9050 http://check.torproject.org; then
	# everything still working
	exit 0
fi

getdate() {
	. /etc/default/htpdate
	# --log_file "$LOG" \
	# --user_agent "$HTTP_USER_AGENT" \
	htpdate \
		--debug \
		--allowed_per_pool_failure_ratio 0.34 \
		--user nobody \
		--done_file    "$HTP_DONE_FILE" \
		--success_file "$HTP_SUCCESS_FILE" \
		--pal_pool     "$HTP_POOL_PAL" \
		--neutral_pool "$HTP_POOL_NEUTRAL" \
		--foe_pool     "$HTP_POOL_FOE"
}

# tor is up but is not working
getdate && service tor restart
