# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.backgroundErrors", 2);
user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1371464520);
user_pref("app.update.lastUpdateTime.background-update-timer", 1371464880);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1371464760);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1371464640);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 71680);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B847b3a00-7ab1-11d4-8f02-006008948af5%7D:1.5.1,it-IT%40dictionaries.addons.mozilla.org:3.3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0");
user_pref("extensions.enigmail.configuredVersion", "1.5.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/opt/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1371394584000}}},{\"name\":\"app-profile\",\"addons\":{\"{847b3a00-7ab1-11d4-8f02-006008948af5}\":{\"descriptor\":\"/home/paranoid/.thunderbird/a0wcqjkh.default/extensions/{847b3a00-7ab1-11d4-8f02-006008948af5}\",\"mtime\":1371464176000},\"it-IT@dictionaries.addons.mozilla.org\":{\"descriptor\":\"/home/paranoid/.thunderbird/a0wcqjkh.default/extensions/it-IT@dictionaries.addons.mozilla.org\",\"mtime\":1371464176000}}}]");
user_pref("extensions.installedDistroAddon.tbtestpilot@labs.mozilla.com", true);
user_pref("extensions.lastAppVersion", "17.0");
user_pref("extensions.lastPlatformVersion", "17.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_html_action", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.imap.use_status_for_biff", false);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.applications.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 0);
user_pref("mail.preferences.display.selectedTabIndex", 1);
user_pref("mail.preferences.security.selectedTabIndex", 0);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "e4f998c0-4879-4571-b8ed-024d6395999");
user_pref("mailnews.database.global.indexer.enabled", false);
user_pref("mailnews.downloadToTempFile", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page_override.mstone", "17.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Lavoro");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personale");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Da fare");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Più tardi");
user_pref("mailnews.tags.version", 2);
user_pref("messenger.startup.action", 0);
user_pref("messenger.status.reportIdle", false);
user_pref("network.cookie.cookieBehavior", 2);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 0);
user_pref("pref.general.disable_button.default_mail", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("purple.conversations.im.send_typing", false);
user_pref("spellchecker.dictionary", "it_IT");
user_pref("toolkit.telemetry.prompted", true);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
