# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.backgroundErrors", 2);
user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1383248978);
user_pref("app.update.lastUpdateTime.background-update-timer", 1371464880);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1383250549);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1383255838);
user_pref("browser.cache.disk.capacity", 102400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 184320);
user_pref("extensions.adblockplus.currentVersion", "2.1");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"es-es@dictionaries.addons.mozilla.org\":{\"version\":\"1.7\",\"type\":\"dictionary\",\"descriptor\":\"/home/paranoid/.icedove/a0wcqjkh.default/extensions/es-es@dictionaries.addons.mozilla.org\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "langpack-it%40thunderbird.mozilla.org:17.0.7,%7B847b3a00-7ab1-11d4-8f02-006008948af5%7D:1.5.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.9");
user_pref("extensions.enigmail.agentAdditionalParam", "--keyserver-options ca-cert-files=/usr/share/ca-certificates/sks-keyservers.crt");
user_pref("extensions.enigmail.configuredVersion", "1.7.2");
user_pref("extensions.enigmail.keyserver", "hkps://hkps.pool.sks-keyservers.net, hkp://ha.pool.sks-keyservers.net");
user_pref("extensions.enigmail.warnGpgAgentAndIdleTime", false);
user_pref("extensions.foxyproxy.firstrun", false);
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"{847b3a00-7ab1-11d4-8f02-006008948af5}\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/{847b3a00-7ab1-11d4-8f02-006008948af5}\",\"mtime\":1383301236000}}},{\"name\":\"app-system-share\",\"addons\":{\"foxyproxy@eric.h.jung\":{\"descriptor\":\"/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/foxyproxy@eric.h.jung\",\"mtime\":1383301270000},\"https-everywhere@eff.org\":{\"descriptor\":\"/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/https-everywhere@eff.org\",\"mtime\":1383301270000},\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\",\"mtime\":1383301270000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-it@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/icedove/extensions/langpack-it@thunderbird.mozilla.org.xpi\",\"mtime\":1372953064000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/icedove/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1383301236000}}},{\"name\":\"app-profile\",\"addons\":{\"es-es@dictionaries.addons.mozilla.org\":{\"descriptor\":\"/home/paranoid/.icedove/a0wcqjkh.default/extensions/es-es@dictionaries.addons.mozilla.org\",\"mtime\":1383306028000}}}]");
user_pref("extensions.installedDistroAddon.tbtestpilot@labs.mozilla.com", true);
user_pref("extensions.lastAppVersion", "17.0.9");
user_pref("extensions.lastPlatformVersion", "17.0.9");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/locale");
user_pref("extensions.ui.locale.hidden", false);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_html_action", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.imap.use_status_for_biff", false);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.applications.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 0);
user_pref("mail.preferences.display.selectedTabIndex", 1);
user_pref("mail.preferences.security.selectedTabIndex", 0);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "a285f5ea-b058-4541-9735-379c71bbfd1");
user_pref("mailnews.database.global.indexer.enabled", false);
user_pref("mailnews.downloadToTempFile", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page_override.mstone", "17.0.9");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Lavoro");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personale");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Da fare");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Più tardi");
user_pref("mailnews.tags.version", 2);
user_pref("messenger.startup.action", 0);
user_pref("messenger.status.reportIdle", false);
user_pref("network.cookie.cookieBehavior", 2);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 0);
user_pref("pref.general.disable_button.default_mail", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("purple.conversations.im.send_typing", false);
user_pref("security.disable_button.openCertManager", false);
user_pref("spellchecker.dictionary", "it_IT");
user_pref("toolkit.telemetry.prompted", true);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");


// disable ad for gandi.net and hover.com
pref("mail.provider.enabled", false);
// don't waste vertical space for useless tab
pref ("mail.tabs.autoHide", true);
